# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-20 21:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('Usuario', models.CharField(max_length=20, unique=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Data_Associacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('Ativo', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('Professor', models.BooleanField(default=False)),
                ('Aluno', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('Nome_Completo', models.CharField(max_length=255)),
                ('Matricula', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('Data_Nascimento', models.DateTimeField(verbose_name='Data de Nascimento')),
                ('Endereco', models.TextField(max_length=200)),
                ('Instituicao', models.CharField(max_length=80, verbose_name='Instituição de Ensino')),
                ('Usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('Nome_Completo', models.CharField(max_length=255)),
                ('Matricula', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('Data_Nascimento', models.DateTimeField(verbose_name='Data de Nascimento')),
                ('Endereco', models.TextField(max_length=200)),
                ('Instituicao', models.CharField(max_length=80, verbose_name='Instituição de Ensino')),
                ('Usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
